name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '.github/**'
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version'
        required: false
        default: '20'
        type: string


#  pull_request_target:
#    branches: [ "main" ]
#    types: [closed]

# Даем разрешения на запись в репозиторий
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

#    if: |
#      (github.event_name == 'push') ||
#      (github.event_name == 'pull_request_target' && github.event.action == 'closed' && github.event.pull_request.merged == true)

    steps:
      # 1. Checkout кода
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Устанавливаем Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      # 3. Устанавливаем зависимости
      - name: Install dependencies
        run: npm ci

      # 4. Собираем проект
      - name: Build
        run: npm run build

      # 5. Настраиваем Pages
      - name: Setup Pages
        uses: actions/configure-pages@v4

      # 6. Загружаем артефакт
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  # Отдельный job для деплоя
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
